const products = [
    // ==================== FRUITS ====================
    {
        id: 1,
        name: 'Organic Bananas',
        price: 28.00,
        requiredQuantity: 50,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'FarmFresh',
        category: 'Fruits',
        rating: 4.8,
        expiryDate: '2026-10-15',
        image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
        available: true,
        description: 'Fresh organic farm bananas in crates.',
        stock: 500
    },
    {
        id: 2,
        name: 'Apples',
        price: 90.00,
        requiredQuantity: 30,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'Shimla Fresh',
        category: 'Fruits',
        rating: 4.7,
        expiryDate: '2026-10-25',
        image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
        available: true,
        description: 'Crisp red apples, graded crate pack.',
        stock: 350
    },
    {
        id: 3,
        name: 'Mangoes',
        price: 80.00,
        requiredQuantity: 40,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'FarmFresh',
        category: 'Fruits',
        rating: 4.9,
        expiryDate: '2026-10-10',
        image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400',
        available: true,
        description: 'Sweet, juicy ripe farm mangoes.',
        stock: 250
    },
    {
        id: 4,
        name: 'Oranges',
        price: 45.00,
        requiredQuantity: 30,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'Nagpur Orchards',
        category: 'Fruits',
        rating: 4.6,
        expiryDate: '2026-10-18',
        image: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400',
        available: true,
        description: 'Juicy oranges, packed with Vitamin C.',
        stock: 300
    },
    {
        id: 5,
        name: 'Grapes',
        price: 65.00,
        requiredQuantity: 25,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'VineRipe',
        category: 'Fruits',
        rating: 4.8,
        expiryDate: '2026-10-12',
        image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400',
        available: true,
        description: 'Sweet seedless green grapes in crates.',
        stock: 200
    },

    // ==================== VEGETABLES ====================
    {
        id: 6,
        name: 'Tomatoes',
        price: 25.00,
        requiredQuantity: 40,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'LocalFarm',
        category: 'Vegetables',
        rating: 4.7,
        expiryDate: '2026-10-08',
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
        available: true,
        description: 'Fresh red ripe farm tomatoes in crates.',
        stock: 450
    },
    {
        id: 7,
        name: 'Green Bell Pepper',
        price: 40.00,
        requiredQuantity: 25,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'FreshMart',
        category: 'Vegetables',
        rating: 4.6,
        expiryDate: '2026-10-12',
        image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400',
        available: true,
        description: 'Crisp green bell peppers / capsicum.',
        stock: 200
    },
    {
        id: 8,
        name: 'Broccoli',
        price: 60.00,
        requiredQuantity: 20,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'GreenField',
        category: 'Vegetables',
        rating: 4.7,
        expiryDate: '2026-10-09',
        image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400',
        available: true,
        description: 'Fresh green broccoli crowns rich in fiber.',
        stock: 150
    },
    {
        id: 9,
        name: 'Carrots',
        price: 32.00,
        requiredQuantity: 30,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'FreshMart',
        category: 'Vegetables',
        rating: 4.5,
        expiryDate: '2026-10-20',
        image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
        available: true,
        description: 'Clean farm carrots in crates.',
        stock: 300
    },
    {
        id: 10,
        name: 'Onions',
        price: 30.00,
        requiredQuantity: 50,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'Nashik Agro',
        category: 'Vegetables',
        rating: 4.6,
        expiryDate: '2026-11-15',
        image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400',
        available: true,
        description: 'Nashik red onions in 50kg mesh bags.',
        stock: 600
    },
    {
        id: 11,
        name: 'Potatoes',
        price: 22.00,
        requiredQuantity: 100,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'AgroRoots',
        category: 'Vegetables',
        rating: 4.6,
        expiryDate: '2026-11-30',
        image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400',
        available: true,
        description: 'Clean farm potatoes in 50kg bulk sacks.',
        stock: 800
    },

    // ==================== CROPS & GRAINS ====================
    {
        id: 12,
        name: 'Rice',
        price: 42.00,
        requiredQuantity: 100,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'KisanGold',
        category: 'Crops',
        rating: 4.8,
        expiryDate: '2027-01-01',
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
        available: true,
        description: 'Premium quality raw rice, freshly harvested.',
        stock: 1200
    },
    {
        id: 13,
        name: 'Wheat',
        price: 28.00,
        requiredQuantity: 100,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'SharbatiHarvest',
        category: 'Crops',
        rating: 4.7,
        expiryDate: '2027-01-01',
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
        available: true,
        description: 'Freshly harvested golden wheat grains.',
        stock: 1500
    },
    {
        id: 14,
        name: 'Corn',
        price: 24.00,
        requiredQuantity: 50,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'FarmFresh',
        category: 'Crops',
        rating: 4.6,
        expiryDate: '2026-12-01',
        image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400',
        available: true,
        description: 'Fresh yellow corn kernels harvested from local farms.',
        stock: 800
    },
    {
        id: 15,
        name: 'Barley',
        price: 26.00,
        requiredQuantity: 50,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'GrainMalt',
        category: 'Crops',
        rating: 4.5,
        expiryDate: '2026-12-01',
        image: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?w=400',
        available: true,
        description: 'Whole barley grains for flour, soups, and malting.',
        stock: 600
    },
    {
        id: 16,
        name: 'Millet',
        price: 38.00,
        requiredQuantity: 50,
        requiredUnit: 'kg',
        unit: 'per kg',
        brand: 'NutriMillets',
        category: 'Crops',
        rating: 4.7,
        expiryDate: '2026-12-01',
        image: 'https://images.unsplash.com/photo-1607672632458-9eb56696346b?w=400',
        available: true,
        description: 'Nutritious pearl millet grains (Bajra), staple crop.',
        stock: 750
    }
];

if (typeof window !== 'undefined') {
    window.products = products;
}